-- AVNT PHASE 6.2 - Reliable Checkout / Anti Duplicate
-- Safe to run multiple times.

alter table public.orders
  add column if not exists client_request_id text,
  add column if not exists checkout_user_agent text,
  add column if not exists checkout_client text;

-- One browser checkout attempt can create at most one order.
create unique index if not exists orders_client_request_id_unique
  on public.orders (client_request_id)
  where client_request_id is not null;

comment on column public.orders.client_request_id is
  'Idempotency key generated by website checkout. Prevents duplicate orders from double tap, retry or lost response.';

comment on column public.orders.checkout_user_agent is
  'Browser/device user-agent captured at checkout for compatibility diagnostics.';

comment on column public.orders.checkout_client is
  'Checkout implementation identifier, e.g. web-reliable-v1.';

select
  column_name,
  data_type,
  is_nullable
from information_schema.columns
where table_schema = 'public'
  and table_name = 'orders'
  and column_name in (
    'client_request_id',
    'checkout_user_agent',
    'checkout_client'
  )
order by column_name;
